name: TemporalVAE
channels:
  - defaults
  - nvidia
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pip:
    # Core dependencies
    - numpy>=1.24.3
    - pandas>=2.0.3
    - scipy>=1.10.1
    - scikit-learn>=1.3.0
    - matplotlib>=3.7.2
    - seaborn>=0.12.2
    - h5py>=3.9.0
    - tqdm>=4.64.1

    # PyTorch ecosystem
    - torch>=2.0.1
    - torchaudio>=2.0.2
    - torchvision>=0.15.2
    - pytorch-lightning>=2.0.4
    - lightning-utilities>=0.9.0

    # Additional utilities
    - tensorboard>=2.13.0
    - protobuf>=3.20.3
    - typing-extensions>=4.5.0
    - requests>=2.28.1
    - pyyaml>=6.0.1
    - setuptools>=65.6.3